apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: full-access-clusterrole-binding
subjects:
- kind: User
  name: "akifbatur"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: full-access-clusterrole
  apiGroup: rbac.authorization.k8s.io
