version: '3.8'

services:
  oracle-db:
    image: harbor.bilisim.com.tr/erp/oracle/database:21.3.0-se2
    container_name: oracle-db
    ports:
      - "1521:1521"
      - "5500:5500"
      - "2484:2484"
    environment:
      ORACLE_SID: ORACLE
      ORACLE_PDB: oraclepdb
      ORACLE_PWD: ABc_12345678#
      INIT_SGA_SIZE: "2048"
      INIT_PGA_SIZE: "4096"
      INIT_CPU_COUNT: "5"
      INIT_PROCESSES: "250"
      ORACLE_EDITION: se
      ORACLE_CHARACTERSET: AL32UTF8
      ENABLE_ARCHIVELOG: "true"
      ENABLE_FORCE_LOGGING: "true"
      ENABLE_TCPS: "true"
    ulimits:
      nofile:
        soft: 1024
        hard: 65536
      nproc:
        soft: 2047
        hard: 16384
      stack:
        soft: 10485760
        hard: 33554432
      memlock:
        soft: 3221225472
        hard: 3221225472
    user: "54321:54321"
    volumes:
      - ~/erp-k8s/oracle/oradata:/opt/oracle/oradata
      - ~/erp-k8s/oracle/startup:/opt/oracle/scripts/startup
      - ~/erp-k8s/oracle/setup:/opt/oracle/scripts/setup
    restart: unless-stopped
