apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: production
type: Opaque
data:
  MYSQL_DATABASE: d29yZHByZXNz
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
  MYSQL_USER: d29yZHByZXNz
  MYSQL_PASSWORD: cGFzc3dvcmQ=
  MYSQL_HOST: bXlzcWwtc2VydmljZQ==
