apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-test
  namespace: test
  labels:
    type: mysql-pv-test
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/mysql-volume