apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv
  namespace: production
  labels:
    type: wp-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/wp-volume